apiVersion: v2
name: ingress-nginx
version: 1.0.0
description: "Wrapper chart for ingress-nginx"

dependencies:
  - name: ingress-nginx
    version: "4.14.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
