apiVersion: v2
name: victoriametrics
version: 1.0.0
description: "Wrapper chart for victoria-metrics-single"

dependencies:
  - name: victoria-metrics-single
    version: "0.28.0"
    repository: "https://victoriametrics.github.io/helm-charts"
