apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-vpn
  namespace: transmission
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gluetun-vpn
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: wireguard
        property: private_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
