services:
  gluetun:
    image: kubernia/gluetun-transmission-cli:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TIMEZONE:-Europe/Kyiv}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Germany
      - SERVER_CITIES=Frankfurt
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c "until transmission-remote 127.0.0.1:9091 -p {{PORTS}} 2>/dev/null; do echo 'Waiting for Transmission to be ready...'; sleep 5; done && echo 'Port {{PORTS}} set successfully'"
      - FIREWALL=on
    volumes:
      - /tmp/gluetun:/tmp/gluetun
      - /run/xtables.lock:/run/xtables.lock
      - /lib/modules:/lib/modules:ro
    ports:
      - 9091:9091
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6@sha256:7ffccac759f5c2f075ab09757b2da1db2c05a35989b5b0c27ae535928c09283f
    container_name: transmission
    depends_on:
      - gluetun
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Europe/Kyiv}
    volumes:
      - ./transmission-config:/config
      - /media/transmission/watch:/watch
      - /media/emby/tv:/downloads/tv
      - /media/emby/movies:/downloads/movies
      - /media/emby/tvanimation:/downloads/tvanimation
      - /media/emby/animation:/downloads/animation
    restart: unless-stopped
