apiVersion: v2
name: cert-manager
version: 1.0.0
description: "Wrapper chart for cert-manager"

dependencies:
  - name: cert-manager
    version: "v1.19.3"
    repository: "https://charts.jetstack.io"
