apiVersion: v2
name: external-secrets
version: 1.0.0
description: "Wrapper chart for external-secrets"

dependencies:
  - name: external-secrets
    version: "1.2.1"
    repository: "https://charts.external-secrets.io"
